# Generated by Django 4.2.2 on 2023-10-28 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dormitory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commandant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dormitory.building')),
            ],
            options={
                'db_table': 'commandant',
            },
        ),
    ]
