# Generated by Django 4.2.2 on 2023-10-28 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import dormitory.models
import dormitory.utils.main_util
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=14)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.CharField(choices=[('1', 'admin'), ('2', 'accountant'), ('3', 'commandant')], max_length=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_date', models.DateField(default=dormitory.models.curr_date)),
                ('book_end', models.DateField(default=dormitory.models.curr_date)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[(1, 'booking'), (2, 'process'), (3, 'canceling')], max_length=20)),
            ],
            options={
                'db_table': 'booking_status',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=25)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('floor_count', models.SmallIntegerField(default=5)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'building',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('director', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'faculty',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dormitory.faculty')),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=25)),
                ('last_name', models.CharField(blank=True, max_length=25)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'principal',
            },
        ),
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=125)),
            ],
            options={
                'db_table': 'privilege',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=4)),
                ('floor', models.PositiveSmallIntegerField()),
                ('is_full', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('person_count', models.SmallIntegerField(default=0)),
                ('room_gender', models.CharField(choices=[('0', 'женшина'), ('1', 'мужчина'), ('2', 'пусто')], default='2', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dormitory.building')),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('place', models.PositiveSmallIntegerField(default=True)),
            ],
            options={
                'db_table': 'room_type',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('sure_name', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('born', models.DateField()),
                ('course', models.CharField(default=1, max_length=1)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('0', 'женшина'), ('1', 'мужчина')], max_length=1)),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=dormitory.utils.main_util.upload_photo)),
                ('nationality', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dormitory.company')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dormitory.country')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dormitory.group')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='StudentType',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('foreigner', 'иностранец'), ('local', 'местный')], max_length=15)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('day', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
            options={
                'db_table': 'student_type',
            },
        ),
        migrations.CreateModel(
            name='TestBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_start', models.DateField(default=dormitory.models.curr_date)),
                ('book_end', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('privilege', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dormitory.privilege')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dormitory.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dormitory.student')),
            ],
            options={
                'db_table': 'test_book',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='student_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dormitory.studenttype'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.roomtype'),
        ),
        migrations.AddField(
            model_name='room',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bill', models.CharField(blank=True, max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('payed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dormitory.booking')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='privilege',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dormitory.privilege'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dormitory.room'),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dormitory.bookingstatus'),
        ),
        migrations.AddField(
            model_name='booking',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dormitory.student'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
