# Generated by Django 4.2.2 on 2023-06-13 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0002_country_city'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='city',
        ),
        migrations.AlterModelTable(
            name='country',
            table='country',
        ),
    ]
