# Generated by Django 4.2.2 on 2023-06-14 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0005_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('place', models.PositiveSmallIntegerField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=25)),
                ('address', models.TextField(blank=True)),
                ('floor_count', models.SmallIntegerField(default=5)),
                ('description', models.TextField(blank=True)),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.principal')),
            ],
        ),
    ]
