# Generated by Django 4.2.2 on 2023-06-14 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0006_roomtype_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='dormitory.principal'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='dormitory.country'),
        ),
    ]
