# Generated by Django 4.2.2 on 2023-06-14 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0007_alter_building_principal_alter_city_country'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='building',
            table='building',
        ),
        migrations.AlterModelTable(
            name='roomtype',
            table='room_type',
        ),
    ]
