# Generated by Django 4.2.2 on 2023-06-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0008_alter_building_table_alter_roomtype_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
