# Generated by Django 4.2.2 on 2023-06-14 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0009_alter_building_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('born', models.DateField()),
                ('address', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(max_length=1)),
                ('student_type', models.CharField(choices=[('foreigner', '1'), ('local', '2')], max_length=9)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dormitory.city')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=4)),
                ('floor', models.PositiveSmallIntegerField()),
                ('is_full', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.building')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.roomtype')),
            ],
        ),
    ]
