# Generated by Django 4.2.2 on 2023-06-14 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0011_alter_student_student_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='room',
            table='room',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
