# Generated by Django 4.2.2 on 2023-06-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0012_alter_room_table_alter_student_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=125)),
            ],
            options={
                'db_table': 'privilege',
            },
        ),
    ]
