# Generated by Django 4.2.2 on 2023-06-15 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0013_privilege'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('privilege', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dormitory.privilege')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dormitory.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dormitory.student')),
            ],
        ),
    ]
