# Generated by Django 4.2.2 on 2023-06-15 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0014_booking'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booking',
            table='booking',
        ),
    ]
