# Generated by Django 4.2.2 on 2023-06-15 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0015_alter_booking_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_type',
        ),
    ]
