# Generated by Django 4.2.2 on 2023-06-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0016_remove_student_student_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentType',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('foreigner', 'иностранец'), ('local', 'местный')], max_length=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
