# Generated by Django 4.2.2 on 2023-06-15 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0017_studenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dormitory.studenttype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studenttype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterModelTable(
            name='studenttype',
            table='student_type',
        ),
    ]
