# Generated by Django 4.2.2 on 2023-07-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0018_student_student_type_alter_studenttype_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('manager', 'manager'), ('student', 'student')], max_length=15),
        ),
    ]
