# Generated by Django 4.2.2 on 2023-07-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0022_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('1', 'admin'), ('2', 'manager'), ('3', 'student')], max_length=1),
        ),
    ]
