# Generated by Django 4.2.2 on 2023-07-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0023_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
