# Generated by Django 4.2.2 on 2023-07-12 17:33

from django.db import migrations, models
import dormitory.models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0026_room_user_alter_room_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='person_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='book_date',
            field=models.DateField(default=dormitory.models.curr_date),
        ),
    ]
