# Generated by Django 4.2.2 on 2023-07-13 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0029_testbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestBooking',
        ),
    ]
