# Generated by Django 4.2.2 on 2023-07-13 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0031_testbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testbooking',
            name='created_at',
        ),
    ]
