# Generated by Django 4.2.2 on 2023-07-13 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0032_remove_testbooking_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='testbooking',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.testbooking')),
            ],
        ),
    ]
