# Generated by Django 4.2.2 on 2023-07-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0033_testbooking_total_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='testbooking',
            name='payed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
