# Generated by Django 4.2.2 on 2023-07-14 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0034_testbooking_payed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
