# Generated by Django 4.2.2 on 2023-07-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0037_alter_building_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
