# Generated by Django 4.2.2 on 2023-07-25 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0039_remove_student_city_student_nationality'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
