# Generated by Django 4.2.2 on 2023-07-25 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0040_delete_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dormitory.country'),
            preserve_default=False,
        ),
    ]
