# Generated by Django 4.2.2 on 2023-08-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0041_student_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('1', 'admin'), ('2', 'manager'), ('3', 'commandant')], max_length=1),
        ),
    ]
