# Generated by Django 4.2.2 on 2023-08-03 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0042_booking_payed_booking_total_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
