# Generated by Django 4.2.2 on 2023-08-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0048_alter_booking_privilege'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
