# Generated by Django 4.2.2 on 2023-08-22 00:24

from django.db import migrations
import dormitory.utils
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0050_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=dormitory.utils.upload_photo),
        ),
    ]
