# Generated by Django 4.2.2 on 2023-09-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0051_alter_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_gender',
            field=models.CharField(choices=[('0', 'empty'), ('1', 'man'), ('2', 'woman')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
